class UserPolicy < ApplicationPolicy
  #Below is generated by the pundit generator
  #class Scope < Struct.new(:user, :scope)
  #  def resolve
  #    scope
  #  end
  #end

  attr_reader :user

  def initialize(user)
    @user = user
  end

  def update?
    user.admin? or user
  end
end
